export const lang = {
    arm: {
        H: 'ժ',
        M: 'մ',
        start: 'Սկսել',
        skip: 'Բաց թողնել',
        sliderTitle1: 'Ընտրեք լիցքավորման կայանը',
        sliderText1: 'Քարտեզի վրա ընտրեք մոտակա կայանը կամ ձեր նախընտրածը, դուք կարող եք անմիջապես ստեղծել երթուղի դեպի այն',
        sliderTitle2: 'Ընտրեք կայանի պորտը և ամրագրեք այն',
        sliderText2: 'Դուք ունեք 20 րոպե ժամանակ լիցքավորման կայարան հասնելու և ներբեռնումը սկսելու համար',
        sliderTitle3: 'Միացրեք էլ.մեքենան և սկսեք լիցքավորել',
        sliderText3: 'Լիցքավորման ավարտին վճարումը կկատարվի ինքնաբերաբար՝ հավելվածի միջոցով',
        sliderTitle4: 'Դիտեք էլ. մեքենայի լիցքը սմարթֆոնում',
        sliderText4: 'Դուք ցանկացած պահի կարող եք վերահսկել ձեր էլ. մեքենայի լիցքը անմիջապես ձեր սմարթֆոնի հավելվածից, և երբ լիցքավորումը ավարտվի, դուք կստանաք ծանուցում',
        filter: 'Ֆիլտեր',
        book: 'Ամրագրել',
        direction: 'Ուղղություն',
        km: 'կմ',
        busy: 'Զբաղված է',
        freedom: 'Ազատ է',
        min: 'րպ.',
        cancel: 'Չեղարկել',
        portTypeTitle: 'Պորտի տեսակը',
        powerTitle: 'հզորություն',
        availability: 'Հասանելիություն',
        filterCheckText1: 'Բոլոր անվճար լիցքավորիչները',
        filterCheckText2: 'Իմ մեքենայի type-երը',
        kw: 'կվտ',
        type: 'Տեսակ',
        Tariff: 'Տարիֆ',
        price: 'Գինը',
        port: 'Պորտ',
        maxPower: 'Առավելագույն հզորություն',
        yourCar: 'Ձեր մեքենան',
        approximatePrice: 'Մոտավոր գինը',
        fillingTime: 'Լիցք. ժամանակ',
        mileageIncrease: 'Վազքի ավելացում',
        chargingLimit: 'Լիցքի լիմիտ',
        selectChargingPercent: 'Ընտրել լիցքավորման տոկոսը',
        charge: 'Լիցքավորել',
        yourCarCharging: 'Ձեր մեքենան լիցքավորվում է',
        yourCarCharged: 'Ձեր մեքենան լիցքավորված է',
        electricity: 'էլ. հոսանք',
        voltage: 'Լարում',
        chargingWatt: 'Լիցքավորման Վտ',
        dram: 'դրամ',
        goToHomeScreen: 'Գնալ գլխավոր էջ',
        cost: 'Արժեք',
        total: 'Ընդհանուր',
    },
    ru: {
        H: 'ч',
        M: 'м',
        start: 'Начинать',
        skip: 'Пропустит',
        sliderTitle1: 'Выберите зарядную станцию',
        sliderText1: 'Выберите ближайшую станцию или понравившуюся на карте, к ней можно сразу проложить маршрут',
        sliderTitle2: 'Выберите порт станции и зафиксируйте его',
        sliderText2: 'У вас есть 20 минут, чтобы добраться до зарядной станции и чтобы начать загрузку',
        sliderTitle3: 'Включите электромобиль и начните зарядку',
        sliderText3: 'Оплата по окончании начисления будет производиться автоматически через приложение',
        sliderTitle4: 'Просмотр электронной почты зарядка автомобиля на смартфоне',
        sliderText4: 'Вы можете контролировать свою электронную почту в любое время. Заряжайте автомобиль прямо из приложения для смартфона и Когда зарядка будет завершена, вы получите уведомление',
        filter: 'Филтер',
        book: 'Бронировать',
        direction: 'Направление',
        km: 'км',
        busy: 'Занято',
        freedom: 'Доступно',
        min: 'мн.',
        cancel: 'Отменить',
        portTypeTitle: 'Тип порта',
        powerTitle: 'Мощность',
        availability: 'Доступность',
        filterCheckText1: 'Все свободные устройства зарядки',
        filterCheckText2: 'Типы моей машины',
        kw: 'квт',
        type: 'Тип',
        Tariff: 'Тариф',
        price: 'Цена',
        port: 'Порт',
        maxPower: 'Максимальная мощь',
        yourCar: 'Ваша машына',
        approximatePrice: 'Приблизительная цена',
        fillingTime: 'Время наполнения',
        mileageIncrease: 'Величина побега',
        chargingLimit: 'Предел зарядки',
        selectChargingPercent: 'Выбрать процент зарядки',
        charge: 'Заряжать',
        yourCarCharging: 'Ваш автомобиль заряжается',
        yourCarCharged: 'Ваш автомобиль заряжаено',
        electricity: 'Электричество',
        voltage: 'Напряжение',
        chargingWatt: 'Зарядка Ватт',
        dram: 'драм',
        goToHomeScreen: 'Перейти на главный экран',
        cost: 'Цена',
        total: 'Всего',
    },
    en: {
        H: 'h',
        M: 'm',
        start: 'Start',
        skip: 'Skip',
        sliderTitle1: 'Select station',
        sliderText1: 'Choose a nearby station or get on the map, if it is possible to pass the route',
        sliderTitle2: 'Select ports and fix it',
        sliderText2: 'It takes you 20 minutes to get to the end of the day and get started',
        sliderTitle3: 'Include the electric car and the starters',
        sliderText3: 'Payment at the end of accrual will be made automatically through the application',
        sliderTitle4: 'View car charging email on smartphone',
        sliderText4: 'You can control your email at any time. Charge your car directly from your smartphone app and you will be notified when charging is complete',
        filter: 'Filter',
        book: 'Book',
        direction: 'Direction',
        km: 'km',
        busy: 'Busy',
        freedom: 'Freedom',
        min: 'min.',
        cancel: 'Cancel',
        portTypeTitle: 'Port Type',
        powerTitle: 'Power',
        availability: 'Availability',
        filterCheckText1: 'All free chargers',
        filterCheckText2: 'My car types',
        kw: 'kw',
        type: 'Type',
        Tariff: 'Tariff',
        price: 'Price',
        port: 'Port',
        maxPower: 'Max Power',
        yourCar: 'Your Car',
        approximatePrice: 'Approximate Price',
        fillingTime: 'Filling Time',
        mileageIncrease: 'Mileage Increase',
        chargingLimit: 'Charging Limit',
        selectChargingPercent: 'Select ChargingPercent',
        charge: 'Charge',
        yourCarCharging: 'Your car is charging',
        yourCarCharged: 'Your car is charged',
        electricity: 'Electricity',
        voltage: 'Voltage',
        chargingWatt: 'Charging Watt',
        dram: 'dram',
        goToHomeScreen: 'Go to home screen',
        cost: 'Cost',
        total: 'Total',
    }
}
