export const lang = {
  ar: {
    H: "ժ",
    M: "ր",
    start: "Սկսել",
    skip: "Բաց թողնել",
    sliderTitle1: "Ընտրեք լիցքավորման կայանը",
    sliderText1: "Քարտեզի վրա ընտրեք մոտակա կայանը կամ ձեր նախընտրածը, դուք կարող եք անմիջապես ստեղծել երթուղի դեպի այն",
    sliderTitle2: "Ընտրեք կայանի պորտը և ամրագրեք այն",
    sliderText2: "Դուք ունեք 20 րոպե ժամանակ լիցքավորման կայարան հասնելու և ներբեռնումը սկսելու համար",
    sliderTitle3: "Միացրեք էլ.մեքենան և սկսեք լիցքավորել",
    sliderText3: "Լիցքավորման ավարտին վճարումը կկատարվի ինքնաբերաբար՝ հավելվածի միջոցով",
    sliderTitle4: "Դիտեք էլ. մեքենայի լիցքը սմարթֆոնում",
    sliderText4: "Դուք ցանկացած պահի կարող եք վերահսկել ձեր էլ. մեքենայի լիցքը անմիջապես ձեր սմարթֆոնի հավելվածից, և երբ լիցքավորումը ավարտվի, դուք կստանաք ծանուցում",
    filter: "Ֆիլտեր",
    book: "Ամրագրել",
    direction: "Ուղղություն",
    km: "կմ",
    busy: "Զբաղված է",
    freedom: "Ազատ է",
    min: "րպ.",
    cancel: "Չեղարկել",
    portTypeTitle: "Պորտի տեսակը",
    powerTitle: "Հզորություն",
    availability: "Հասանելիություն",
    filterCheckText1: "Բոլոր ազատ լիցքավորիչները",
    filterCheckText2: "Իմ մեքենայի type-երը",
    kw: "կվտ",
    type: "Տեսակ",
    Tariff: "Տարիֆ",
    price: "Գինը",
    port: "Պորտ",
    maxPower: "Առավելագույն հզորություն",
    yourCar: "Ձեր մեքենան",
    approximatePrice: "Մոտավոր գինը",
    fillingTime: "Լիցք. ժամանակ",
    mileageIncrease: "Վազքի ավելացում",
    chargingLimit: "Լիցքի լիմիտ",
    selectChargingPercent: "Ընտրել լիցքավորման տոկոսը",
    charge: "Լիցքավորել",
    yourCarConnecting: "Ձեր մեքենան միանում է",
    yourCarCharged: "Ձեր մեքենան լիցքավորում է",
    electricity: "էլ. հոսանք",
    voltage: "Լարում",
    chargingWatt: "Լիցքավորման Վտ",
    dram: "դրամ",
    goToHomeScreen: "Գնալ գլխավոր էջ",
    cost: "Արժեք",
    total: "Ընդհանուր",
    signIn: "Մուտք",
    signUp: "Գրանցվել",
    settings: "Կարգավորումներ",
    otherSections: "Այլ բաժիններ",
    notifications: "Ծանուցումներ",
    notification: "Ծանուցում",
    getNotification: "Ստանալ ծանուցումները",
    lang: "Լեզու",
    help: "Օգնություն",
    faq: "ՀՏՀ",
    Ask: "Հարց տալ",
    appInfo: "Հավելվածի մասին",
    appInfoText1: "Ծրագիրը կօգնի ձեզ լիցքավորել մեքենան ընդամենը մի քանի հպումով, որը կխնայի Ձեր ժամանակը, ֆինանսական և այլ ռեսուրսներ։ Քարտեզի միջոցով կարող եք ակնթարթորեն տեսնել մոտակա լիցքավորման կայանը, ստանալ տեղեկատվություն կայանի մասին և օգտվել համապատասխան ծառայությունից։",
    appInfoText2: "Շատ համակարգչային տպագրական ծրագրեր և ինտերնետային էջերի խմբագրիչներ այն օգտագործում են որպես իրենց ստանդարտ տեքստային մոդել, և հետևապես, ինտերնետում  որոնման արդյունքում կարելի է հայտնաբերել էջեր, որոնք դեռ նոր են կերտվում: Ժամանակի ընթացքում ձևավորվել են Lorem Ipsum-ի տարբեր վերսիաներ` երբեմն ներառելով պատահական տեքստեր, երբեմն էլ հատուկ իմաստ (հումոր և նմանատիպ բովանդակություն):",
    partner: "Գործընկերներ",
    weOnSocial: "Մենք սոց. կայքերում",
    languageSelection: "Ընտրել լեզուն",
    question: "Հարց",
    send: "Ուղարկել",
    name: "Անուն",
    surname: "Ազգանուն",
    phone: "Հեռախոս",
    email: "Էլ. Հասցե",
    mail: "Հաղոդագրություն",
    enter: "Մուտք",
    exit: "Դուրս գալ",
    balance: "Բալանս",
    password: "Գաղտնաբառ",
    newPassword: "Նոր գաղտնաբառ",
    rpassword: "Կրկնել գաղտնաբառ",
    rememberPassword: "Մոռացել եք Ձեր գաղտնաբառը",
    rememberPasswordTitle: "Մոռացել եք Ձեր գաղտնաբառը",
    changePassword: "Փոխել գաղտնաբառը",
    confirmCode: "Հաստատել կոդը",
    confirm: "Հաստատել",
    confirmText: "Ձեր հեռախոսին կգա sms հախորդագրություն առկա կոդով։ Խնդրումենք լրացնել այս կոդը լրացնել այս դաշտում և հաստատել հեռախոսահամարը։",
    code: "Կոդ",
    changePasswordTitle: "Գաղտնաբառի փոփոխում",
    registration: "Գրանցվել",
    wrongName: "Սխալ անուն",
    wrongЕmail: "Սխալ էլ.փոստ",
    wrongPassword: "Սխալ գաղտնաբառ",
    wrongNewPassword: "Սխալ նոր գաղտնաբառը",
    wrongRpNewPassword: "Սխալ կրկնվող գաղտնաբառ",
    wrongPhone: "Սխալ հեռախոս",
    wrongSelectAuto: "Դուք պետք է ընտրեք մեքենա",
    wrongSelectAutoModal: "Դուք պետք է ընտրեք մեքենայի մոդելը",
    youAreNotRegistered: "Գրանցված չեք",
    writeYourEmailAddressAndFollowTheMarkedFootprints: "Գրեք ձեր էլ.հասցեն և հետևեք նշված քայլերին",
    topUpBalance: "Համալրել բալանսը",
    titleBalance: "Բալանսի համալրում",
    personalInformation: "Անձնական տվյալներ",
    contactUs: "Կապվեք մեզ հետ",
    history: "Պատմություն",
    addNewCard: "Ավելացնել նոր քարտ",
    money: "Գումար",
    yourPaymentInformationIsSecureWithUs: "Ձեր վճարային ինֆորմացիան ապահով է մեզ հետ",
    add: "Համալրել",
    save: "Պահպանել",
    inputs: "Մուտքեր",
    outputs: "Ելքեր",
    totalPrice: "Ընդհանուր գումար",
    totalCharge: "Ընդհանուր լիցքավորում",
    cards: "Քարտեր",
    yourNewPasswordSentYourEmail: "Ձեր նոր գաղտնաբառը ուղարկվել է ձեր էլ. հասծեին",
    sendAgain: "Կրկին ուղարկել",
    view: "Դիտել",
    areYouSureYouWantToDeleteTheCard: "Դուք վստահ եք ջնջել քարտը?",
    pleaseLoginInProgram: "Խնդրում ենք մուտք գործել ծրագիր",
    noCardsAddedYet: "Ավելացված քարտեր դեռ չկան",
    logIn: "Մուտք",
    delete: "Ջնջել",
    stop: "Դադարել",
    amount: "Գումարը",
    charged: "Լիցքավորվաում",
    charging: "Լիցքավորում է",
    stationName: "Կայանի անվանումը",
    dateAndTime: "Ամսաթիվ և ժամ",
    payment: "Վճարում",
    costs: "արժե",
    iAgreeWithTheRules: "Համաձայն եմ կանոնների հետ",
    car: "Մեքենա",
    make: "Մակնիշ",
    theOldPasswordIsTheSameAsTheNewPassword: "Հին գաղտնաբառը նույնն է, ինչ նոր գաղտնաբառը",
    chooseAuto: "Ընտրեք մեքենա",
    chooseModal: "Ընտրեք մոդել",
    search: "Որոնել",
    list: "Ցուցակ",
    atLeastOneUppercase: "Առնվազն մեկ մեծատառ",
    atLeastOneLowercase: "Առնվազն մեկ փոքրատառ",
    atLeastOneDigit: "Առնվազն մեկ թվանշան",
    atLeastOneSpecialCharacters: "Առնվազն մեկ Հատուկ նիշ",
    atLeastMinimumCharacters: "Առնվազն 8 նիշ",
    permissionToAccessLocationWasDenied: "Գտնվելու վայրի թույլտվությունը մերժվել է",
    permissionToAccessCameraWasDenied: "Տեսախցիկի թույլտվությունը մերժվել է",
    doYouNoHaveHistory: "Դուք պատմություն չունեք",
    doYouNoHaveNotification: "Դուք ծանուցում չունեք",
    number: "Հ",
    thePortIsBusyOrUnavailable: "Միացման կետը զբաղված է կամ անհասանելի է",
    deleteAccount: "Ջնջել Օգտատերին",
    аreYouWantToDeleteYourAccount: "Դուք ուզում եք ջնջել ձեր հաշիվը",
    text: "տեքստ",
  },
  ru: {
    H: "ч",
    M: "м",
    start: "Начинать",
    skip: "Пропустит",
    sliderTitle1: "Выберите зарядную станцию",
    sliderText1: "Выберите ближайшую станцию или понравившуюся на карте, к ней можно сразу проложить маршрут",
    sliderTitle2: "Выберите порт станции и зафиксируйте его",
    sliderText2: "У вас есть 20 минут, чтобы добраться до зарядной станции и чтобы начать загрузку",
    sliderTitle3: "Включите электромобиль и начните зарядку",
    sliderText3: "Оплата по окончании начисления будет производиться автоматически через приложение",
    sliderTitle4: "Просмотр электронной почты зарядка автомобиля на смартфоне",
    sliderText4: "Вы можете контролировать свою электронную почту в любое время. Заряжайте автомобиль прямо из приложения для смартфона и Когда зарядка будет завершена, вы получите уведомления",
    filter: "Фильтр",
    book: "Бронировать",
    direction: "Направление",
    km: "км",
    busy: "Занято",
    freedom: "Доступно",
    min: "мн.",
    cancel: "Отменить",
    portTypeTitle: "Тип порта",
    powerTitle: "Мощность",
    availability: "Доступность",
    filterCheckText1: "Все свободные устройства зарядки",
    filterCheckText2: "Типы моей машины",
    kw: "квт",
    type: "Тип",
    Tariff: "Тариф",
    price: "Цена",
    port: "Порт",
    maxPower: "Максимальная мощь",
    yourCar: "Ваша машына",
    approximatePrice: "Приблизительная цена",
    fillingTime: "Время наполнения",
    mileageIncrease: "Величина побега",
    chargingLimit: "Предел зарядки",
    selectChargingPercent: "Выбрать процент зарядки",
    charge: "Заряжать",
    yourCarConnecting: "Ваш автомобиль подклучается",
    yourCarCharged: "Ваш автомобиль заряжается",
    electricity: "Электричество",
    voltage: "Напряжение",
    chargingWatt: "Зарядка Ватт",
    dram: "драм",
    goToHomeScreen: "Перейти на главный экран",
    cost: "Цена",
    total: "Всего",
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    settings: "Настройки",
    otherSections: "Другие разделы",
    notifications: "Уведомления",
    notification: "Уведомления",
    getNotification: "Получать уведомления",
    lang: "Язык",
    help: "Помощь",
    faq: "Инфо",
    Ask: "Задать вопрос",
    appInfo: "О приложении",
    appInfoText1: "Программа поможет зарядить автомобиль всего в несколько нажатий, что сэкономит ваше время, деньги и другие ресурсы. С помощью карты можно мгновенно увидеть ближайшую зарядную станцию, получить информацию о станции и воспользоваться соответствующим сервисом.",
    appInfoText2: "Многие компьютерные программы для печати и редакторы веб-страниц используют его в качестве стандартной текстовой модели և затем поищите в Интернете. В результате вы можете найти страницы, которые все еще только строятся. Формируется со временем разные версии Lorem Ipsum, иногда включая случайные тексты, иногда особый смысл (юмор и подобный содержание):",
    partner: "Партнеры",
    weOnSocial: "Мы в соц. сетях",
    languageSelection: "Выбор языка",
    question: "Вопрос",
    send: "Отправить",
    name: "Имя",
    surname: "Фамилия",
    phone: "Телефон",
    email: "Эл. адрес",
    mail: "Почта",
    enter: "Войти",
    exit: "Выход",
    balance: "Баланс",
    password: "Пароль",
    newPassword: "Новый пароль",
    rpassword: "Повторите пароль",
    rememberPassword: "Забыли ваш пароль",
    changePassword: "Изменить пароль",
    confirmCode: "Подтвердить код",
    confirm: "Подтвердить",
    confirmText: "На ваш телефон придет sms-сообщение с доступным кодом. Пожалуйста, введите этот код в это поле և подтвердите номер телефона.",
    code: "Код",
    changePasswordTitle: "Изменить пароль",
    registration: "Регистрация",
    wrongЕmail: "Неверный адрес эл. почты",
    wrongName: "Неверный имя",
    wrongPassword: "Неправильный пароль",
    wrongNewPassword: "Неправильный новый пароль",
    wrongRpNewPassword: "Неправильный повтареный пароль",
    wrongPhone: "Неверный телефон",
    wrongSelectAuto: "Необходимо выбрать автомобиль",
    wrongSelectAutoModal: "Необходимо выбрать модель автомобиля",
    youAreNotRegistered: "Вы не зарегистрированы",
    writeYourEmailAddressAndFollowTheMarkedFootprints: "Напишите ваш электронный адрес и следите по отмеченным следам",
    topUpBalance: "Пополнить баланс",
    titleBalance: "Пополнения баланса",
    personalInformation: "Персональная информация",
    contactUs: "Свяжитесь с нами",
    history: "История",
    addNewCard: "Добавить новую карту",
    money: "Деньги",
    yourPaymentInformationIsSecureWithUs: "Ваша платежная информация в безопасности с нами",
    add: "Добавить",
    save: "Сохранить",
    inputs: "Ввод",
    outputs: "Вывод",
    totalPrice: "Общая цена",
    totalCharge: "Общая зарядка",
    cards: "Карты",
    yourNewPasswordSentYourEmail: "Ваш новый пароль отправлен на вашу электронную почту",
    sendAgain: "Отправить снова",
    view: "Посмотреть",
    areYouSureYouWantToDeleteTheCard: "Вы уверены, что хотите удалить карту?",
    pleaseLoginInProgram: "Пожалуйста войдите в программу",
    noCardsAddedYet: "Карты еще не добавлены",
    logIn: "Авторизоваться",
    delete: "Удалить",
    stop: "Остоновить",
    amount: "Сумма",
    charged: "Заряжено",
    charging: "Заряжается",
    stationName: "Название станции",
    dateAndTime: "Дата и время",
    payment: "Оплата",
    costs: "стоит",
    iAgreeWithTheRules: "Я согласен с правилами",
    car: "Машина",
    make: "Марка",
    theOldPasswordIsTheSameAsTheNewPassword: "Старый пароль совпадает с новым паролем",
    chooseAuto: "Выбратье авто",
    chooseModal: "Выбратье модел",
    search: "Поиск",
    list: "Список",
    atLeastOneUppercase: "Хотя бы один верхний регистр",
    atLeastOneLowercase: "Хотя бы один нижний регистр",
    atLeastOneDigit: "Хотя бы одна цифра",
    atLeastOneSpecialCharacters: "Хотя бы один специальный символ",
    atLeastMinimumCharacters: "Минимум 8 символов",
    permissionToAccessLocationWasDenied: "Разрешение на доступ к местоположению было отклонено",
    permissionToAccessCameraWasDenied: "Разрешение на доступ к камере было отклонено",
    doYouNoHaveHistory: "У вас нет истории",
    doYouNoHaveNotification: "У вас нет уведомления",
    number: "Н",
    thePortIsBusyOrUnavailable: "Порт занят или недоступен",
    deleteAccount: "Удалить аккаунт",
    аreYouWantToDeleteYourAccount: "Вы хотите удалить свой аккаунт?",
    text: "текст"
  },
  en: {
    H: "h",
    M: "m",
    start: "Start",
    skip: "Skip",
    sliderTitle1: "Select station",
    sliderText1: "Choose a nearby station or get on the map, if it is possible to pass the route",
    sliderTitle2: "Select ports and fix it",
    sliderText2: "It takes you 20 minutes to get to the end of the day and get started",
    sliderTitle3: "Include the electric car and the starters",
    sliderText3: "Payment at the end of accrual will be made automatically through the application",
    sliderTitle4: "View car charging email on smartphone",
    sliderText4: "You can control your email at any time. Charge your car directly from your smartphone app and you will be notified when charging is complete",
    filter: "Filter",
    book: "Book",
    direction: "Direction",
    km: "km",
    busy: "Busy",
    freedom: "Free",
    min: "min.",
    cancel: "Cancel",
    portTypeTitle: "Port Type",
    powerTitle: "Power",
    availability: "Availability",
    filterCheckText1: "All free chargers",
    filterCheckText2: "My car types",
    kw: "kw",
    type: "Type",
    Tariff: "Tariff",
    price: "Price",
    port: "Port",
    maxPower: "Max Power",
    yourCar: "Your Car",
    approximatePrice: "Approximate Price",
    fillingTime: "Filling Time",
    mileageIncrease: "Mileage Increase",
    chargingLimit: "Charging Limit",
    selectChargingPercent: "Select ChargingPercent",
    charge: "Charge",
    yourCarConnecting: "Your car is connecting",
    yourCarCharged: "Your car is charging",
    electricity: "Electricity",
    voltage: "Voltage",
    chargingWatt: "Charging Watt",
    dram: "dram",
    goToHomeScreen: "Go to home screen",
    cost: "Cost",
    total: "Total",
    signIn: "Sign In",
    signUp: "Sign Up",
    settings: "Settings",
    otherSections: "Other Sections",
    notifications: "Notifications",
    notification: "Notification",
    getNotification: "Receive Notifications",
    lang: "Language",
    help: "Help",
    faq: "Faq",
    Ask: "Ask question",
    appInfo: "About the app",
    appInfoText1: "The program will help you charge the car with just a few taps, which will save you time, money and other resources. Using the map, you can instantly see the nearest charging station, get information about the station and use the corresponding service.",
    appInfoText2: "Many computer printing software and web page editors use it as their standard text model, and then search the internet for Lorem Ipsum As a result, you can find pages that are still are just being built. Formed over time are different versions of Lorem Ipsum, sometimes including random texts, sometimes special meaning (humor and similar content):",
    partner: "Partners",
    weOnSocial: "We on social",
    languageSelection: "Language selection",
    question: "Question",
    send: "Send",
    name: "Name",
    surname: "Surname",
    phone: "Phone",
    email: "Email",
    mail: "Mail",
    enter: "Login",
    exit: "Exit",
    balance: "Balance",
    password: "Password",
    newPassword: "New Password",
    rpassword: "Repeat password",
    rememberPassword: "Forgot your password",
    changePassword: "Change Password",
    confirmCode: "Confirm code",
    confirm: "Confirm",
    confirmText: "An SMS with the available code will arrive on your phone. Please fill in this code in this field and confirm the phone number.",
    code: "Code",
    changePasswordTitle: "Change Password",
    registration: "Registration",
    wrongЕmail: "Wrong email address",
    wrongName: "Wrong name",
    wrongPassword: "Wrong password",
    wrongNewPassword: "Wrong new password",
    wrongRpNewPassword: "Wrong repeat password",
    wrongPhone: "Wrong phone",
    wrongSelectAuto: "Must choose auto",
    wrongSelectAutoModal: "Must choose car model",
    youAreNotRegistered: "You are not registered",
    writeYourEmailAddressAndFollowTheMarkedFootprints: "Write your email address and follow the marked footprints",
    topUpBalance: "Top up balance",
    titleBalance: "Complete balance",
    personalInformation: "Personal information",
    contactUs: "Contact us",
    history: "History",
    addNewCard: "Add new card",
    money: "Money",
    yourPaymentInformationIsSecureWithUs: "Your payment information is secure with us",
    add: "Add",
    save: "Save",
    inputs: "Inputs",
    outputs: "Outputs",
    totalPrice: "Total Price",
    totalCharge: "Total Charge",
    cards: "Cards",
    yourNewPasswordSentYourEmail: "Your new password sent your email",
    sendAgain: "Send again",
    view: "View",
    areYouSureYouWantToDeleteTheCard: "Are you sure you want to delete the card?",
    pleaseLoginInProgram: "Please login in program",
    noCardsAddedYet: "No cards added yet",
    logIn: "Login",
    delete: "Delete",
    stop: "Stop",
    amount: "Amount",
    charged: "Charged",
    charging: "Charging",
    stationName: "Station name",
    dateAndTime: "Date and time",
    payment: "Payment",
    costs: "costs",
    iAgreeWithTheRules: "I agree with the rules",
    car: "Car",
    make: "Make",
    theOldPasswordIsTheSameAsTheNewPassword: "Тhe old password is the same as the new password",
    chooseAuto: "Choose auto",
    chooseModal: "Choose modal",
    search: "Search",
    list: "List",
    atLeastOneUppercase: "At least one Uppercase",
    atLeastOneLowercase: "At least one Lowercase",
    atLeastOneDigit: "At least one digit",
    atLeastOneSpecialCharacters: "At least one special characters",
    atLeastMinimumCharacters: "At least minimum 8 characters",
    permissionToAccessLocationWasDenied: "Permission to access location was denied",
    permissionToAccessCameraWasDenied: "Permission to access camera was denied",
    doYouNoHaveHistory: "You have not history",
    doYouNoHaveNotification: "You have not notification",
    number: "N",
    thePortIsBusyOrUnavailable: "The port is Busy or Unavailable",
    deleteAccount: "Delete account",
    аreYouWantToDeleteYourAccount: "Are you want to delete your account?",
    text: "text"
  }
}
